"""add bill type into bill_version

Revision ID: 3263a8f198b0
Revises: 7a9b38559992
Create Date: 2022-12-10 20:00:48.611280

"""

# revision identifiers, used by Alembic.
revision = '3263a8f198b0'
down_revision = '7a9b38559992'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_version', sa.Column('bill_type', sa.UnicodeText(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    pass
    # ### end Alembic commands ###
