"""added tag column to bill model

Revision ID: 49fc258cebf5
Revises: 927ed575acbd
Create Date: 2020-04-23 13:13:08.094805

"""

# revision identifiers, used by Alembic.
revision = "49fc258cebf5"
down_revision = "927ed575acbd"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bill", sa.Column("tag", sa.UnicodeText(), nullable=True))
    op.add_column(
        "bill_version",
        sa.Column("tag", sa.UnicodeText(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bill_version", "tag")
    op.drop_column("bill", "tag")
    # ### end Alembic commands ###
