"""empty message

Revision ID: 52903c4b2459
Revises: 6c6fb2b7f229
Create Date: 2019-10-20 20:31:49.848058

"""

# revision identifiers, used by Alembic.
revision = "52903c4b2459"
down_revision = "6c6fb2b7f229"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bill", sa.Column("type", sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bill", "type")
    # ### end Alembic commands ###
