"""empty message

Revision ID: df95884d26ae
Revises: a67119aa3ee5
Create Date: 2019-09-15 23:17:29.721176

"""

# revision identifiers, used by Alembic.
revision = 'df95884d26ae'
down_revision = 'a67119aa3ee5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('document', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bill', 'document')
    # ### end Alembic commands ###
